### ISSUE TITLE
GoTo Definition Stopped Working Between 0.9 and 0.10

### ISSUE THREAD

**Issue by JohnMarzulli** [rubyide/vscode-ruby#86]
### Your environment
- `vscode-ruby` version: 0.10
- Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
- VS Code version: 1.6.1
- Operating System: El Capitan
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !
### Expected behavior

Right clicking on a function will show "goto definition" and "peek definition"
### Actual behavior

Right clicking on a function shows "Change all occurences", "cut", "copy", and "paste" only.
### Steps to reproduce the problem

Upgrade from Ruby 0.9x to Ruby 0.10x
No configuration was changed between the upgrade

**Comment by HookyQR** [comment]
Hey @JohnMarzulli, this should be fixed, and you please let us know how this is at your end now.

**Comment by gobijan** [comment]
Go to definition works for me.

**Comment by JohnMarzulli** [comment]
Not working. The "Goto Definition" option in the right click context menu is still missing.

I verified I have Ruby Plugin 0.10.3
VS-Code: 1.7.1
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

I have an empty (default) workspace settings file.

My User setting.jsons file is:
`
// Place your settings in this file to overwrite the default settings
{
    "editor.autoClosingBrackets": false,
    "editor.tabSize": 2,
    "editor.formatOnType": true,
    "ruby.rubocop.onSave": true,
    "ruby.rubocop.configFilePath": "/Users/john.marzulli/rubocop.yml",
    // Basic settings: turn linter(s) on
    "ruby.lint": {
        "reek": true,
        "ruby.lint": {
            "rubocop": true,
            "ruby": true, //Runs ruby -wc
            "fasterer": true,
            "debride": true,
            "ruby-lint": true
        }
    },
    "ruby.locate": {
        "include": "**/*.rb"
    },
    "ctags": {
        "executePath": "/Users/john.marzulli/.rvm/gems/ruby-2.2.4/bin/ripper-tags",
        "options": "--tag-file=.tags --recursive --force --exclude=/assets/ --exclude=.bundle --exclude=.git/ --exclude=coverage/ --exclude=.arcanist-extensions/ --exclude=log/ --exclude=tmp/ --exclude=bin/",
        "fileName": ".tags"
    }
}
`

**Comment by HookyQR** [comment]
@JohnMarzulli: This is truely weird. As long as you have a folder open, this should work. The only time the Go to Definition is disabled is when there is no workspace root. 

Can you check if there are any errors being reported in the console please. (Help->Toggle Developer Tools->{Open console tab})

**Comment by JohnMarzulli** [comment]
extensionHost.ts:255 [Extension Host] Activating extension `rebornix.Ruby` failed:  lintBuilders[l] is not a constructorI.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255 [Extension Host] Here is the error stack:  TypeError: lintBuilders[l] is not a constructor
    at Linter._runLinters (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/lint/lib/linter.js:95:16)
    at Linter.run (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/lint/lib/linter.js:31:15)
    at LintCollection.run (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/lint/lintCollection.js:17:34)
    at changeTrigger (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/ruby.js:145:11)
    at Array.forEach (native)
    at activate (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/ruby.js:160:35)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14861)
    at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14644)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14516
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:5732)

[Extension Host] Here is the error stack:  TypeError: lintBuilders[l] is not a constructor
    at Linter._runLinters (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/lint/lib/linter.js:95:16)
    at Linter.run (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/lint/lib/linter.js:31:15)
    at LintCollection.run (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/lint/lintCollection.js:17:34)
    at changeTrigger (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/ruby.js:145:11)
    at Array.forEach (native)
    at activate (/Users/john.marzulli/.vscode/extensions/rebornix.Ruby-0.10.3/ruby.js:160:35)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14861)
    at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14644)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14516
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:5732)

**Comment by radar** [comment]
I was pairing with @jhuangnz today and we discovered this issue was caused by a missing `solargraph` gem. We installed the gem, restarted the editor and "Go to Definition" and Cmd+Click started working again :D

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
